language: julia

os:
- linux
- osx

julia:
# - 0.7
- 1.0
- 1.1
- nightly

matrix:
  allow_failures:
  - julia: nightly
  - julia: 0.7
  fast_finish: true

notifications:
  email: false

cache:
  timeout: 1000
  directories:
  - downloads

env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true

stages:
- name: dylib
- name: test

jobs:
  include:
  - stage: dylib
    julia: 1.0
    script:
    - julia -e 'using Pkg; Pkg.add("BinaryProvider"); Pkg.add("BinaryBuilder");'
    - julia deps/build_tarballs.jl
    deploy:
      provider: releases
      api_key:
        secure: Bgz6GD7kcWQQRijf/zn8nD8wcyhjrjm9c4YBIDAdxPENiem3UOgmUjQCUieGxHFAjyCqmITyjNv9I4xPtjJqJQG1dpH9tlnzPmFGz2YqdYOyh6c9GbSLuMSy+ypVX88VA9KAahCgtPnF7MT07MX4JfMZo8X9piyRTPEV/0AX8P5EPNvg9PjdRtTk0zowMXlF30TYmsZb6vu+j4Ry9Bmn2oQhzGfqEgzoMI+Zp0w0ySjjKtHwoVerGB4zEAysq+RUcoCb3BxXROyD9mj6hL66KZCjlsTUAZ3paFDVqVTOy+b5Rul/7RM0iUKPpYAv0FDyw1rPhtbQpHFUY1VJmHJRWVCudrywJXiqti6IllTteR6RB1yb3a8KP7pX6cg2/zr96yXKiUtNcV5mzt1Ubaue2aESW1r3JoMmvHj7i9vjvW+IazPkY4Sx3iQ5TmCNMNnXZg1EzFFlEkn3DM206Ao9AVyxbGnjf63zNB5FSRh6MLGP4RKeSGTdYdryTPEt30Jhu9wPIT7d2cC2lIt2fqU8aS8PCL03NYHw6MOITM/xqFYYusC+XYSxt7WvQIYHyvIkNUjA7LxbMEuEy9Nd/HlWWQsxuegYb9jKInWiTfdUIEn5/eG7hvJ5XfpMZlaNZODeId+0MTq1foQTehriXrnkSJrWeRjyOXFAEWGs67EJwAQ=
      file_glob: true
      skip_cleanup: true
      file: products/*
      on:
        repo: TuringLang/Libtask.jl
        tags: true
  - stage: test
    script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.build("Libtask"); Pkg.test("Libtask", coverage=true)'
    # - julia -e 'using Pkg; cd(Pkg.dir("Libtask")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
