name: Integration Test (AdvancedPS)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: AdvancedPS.jl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - uses: julia-actions/cache@v2

      - uses: actions/checkout@v6
        with:
          repository: TuringLang/AdvancedPS.jl
          ref: main
          path: downstream

      - name: Run downstream tests with this Libtask
        shell: julia --color=yes --project=downstream {0}
        run: |
          using Pkg
          try
            Pkg.develop(PackageSpec(path="."))
            Pkg.update()
            Pkg.test()
          catch err
            err isa Pkg.Resolve.ResolverError || rethrow()
            @info "Not compatible with this release. No problem." exception=err
            exit(0)
          end
